title: "Your Name"
description: "Personal Academic Homepage"
url: "https://yourname.github.io"
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# 站点信息
name: "Your Name"
locale: "en-US"   # 或 zh-CN
repository: yourname/yourname.github.io

# 导航
collections:
  posts:
    output: true
  pages:
    output: true

# 外观
minimal_mistakes_skin: "default"   # 可选: air, aqua, sunrise, dark等
logo: "/assets/img/avatar.png"     # 可选头像
masthead_title: "Your Name"

# 插件
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Markdown / 公式
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# 评论/统计(可选)
# google_analytics: "G-XXXXXXX"

# 导航数据文件
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
