title: "Zhijian Zhou"
description: "Personal academic homepage & blog"
theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope: {path: "", type: "pages"}
    values: {layout: single, author_profile: true}
  - scope: {path: "", type: "posts"}
    values: {layout: single, author_profile: true}
