title: "Zhijian Zhou"
description: "Personal academic homepage & blog"

# ❌ 删掉这行（会去找本地Gem）
# theme: minimal-mistakes-jekyll

# ✅ 只用 remote_theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 页面/文章的默认布局
defaults:
  - scope: { path: "", type: "pages" }
    values: { layout: single, author_profile: true }
  - scope: { path: "", type: "posts" }
    values: { layout: single, author_profile: true }
